services:
  infracalendar:
    build: .
    image: infracalendar:latest
    depends_on:
      - infracalendar_db
    environment:
      - AUTH_TOKEN=secret
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATABASE_URL=postgresql://infracalendar:infracalendar_pass@infracalendar_db:5432/infracalendar_db
      - CRAWLERS_URL=http://host.docker.internal:8002
    ports:
      - "8003:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  infracalendar_db:
    image: postgres:14
    environment:
      POSTGRES_USER: infracalendar
      POSTGRES_PASSWORD: infracalendar_pass
      POSTGRES_DB: infracalendar_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "15433:5432"

volumes:
  db_data:
